### ISSUE TITLE
File gets detected by windows defender

### ISSUE THREAD

**Issue by bill0alt** [OdiLock/Patrick-Crypter#2]
I did not try using this encrypter with an antivirus but it gets detected by the windows 10 defender

**Comment by bill0alt** [comment]
Ok thank you. Do you know when you plan to update the files?
- Do you know any crypter that can bypass Windows defender for now?
- And why did you write in the readme that we should not upload the files to virustotal?
Thank you for the answer

**Comment by OdiLock** [comment]
Virustotal sends a crypter file to the antivirus database, which will prevent your file from being encrypted
