### ISSUE TITLE
almost full detect 

### ISSUE THREAD

**Issue by DataReset** [OdiLock/Patrick-Crypter#4]
![image](https://user-images.githubusercontent.com/81904251/192052710-4d6dd3bd-b086-469a-b916-e54dd8ff3e04.png)

**Comment by OdiLock** [comment]
I will update the stub later, the main thing is that windows defender does not see it

**Comment by DataReset** [comment]
![image](https://user-images.githubusercontent.com/81904251/192293650-a3ec061e-e0a2-4508-8b2f-91ec002c17d0.png)
detect now
